platform :ios, '9.0'

use_frameworks!

def main_pods
    pod 'Alamofire'
    pod 'swift-mimic', :path => '../'
end

target 'swift-mimic_Example' do
    main_pods
end

target 'swift-mimic-ExampleTest' do
    main_pods
end

# Referenced from the discussion here(https://github.com/CocoaPods/CocoaPods/issues/8139).
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # This works around a unit test issue introduced in Xcode 10.
            # We only apply it to the Debug configuration to avoid bloating the app size
            if config.name == "Debug" && defined?(target.product_type) && target.product_type == "com.apple.product-type.framework"
                config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = "YES"
            end
        end
    end
end
